# basic options
title: Sunil Raj
author: Sunil Raj Shanmugham
email: vssunilraj@gmail.com
description: This my personal and feel free to contact me anytime through platforms given above.
twitter_username: vssunilraj
github_username: PVSSLR

# Build settings
markdown: kramdown
theme: minima
